### ISSUE TITLE
Edit: Render process gone?

### ISSUE THREAD

**Issue by Hassall** [dfcreative/save-file#15]
~~I believe there is a limit for the blob/file size or else it will fail Didn't see anything in the readme, you might want to include that. Ill edit if I find out the max file size.~~ 

~~Only tested 2 files: fails on 1GB, works for 100MB.~~ 

**Edit:**

NVM about the file size. Tested with another 1GB file and it worked fine. But for some reason, I'm getting "Render process gone" on one specific file. Any idea why?

**Comment by HaleemDream** [comment]
Yeah I saw that as well when I searched, I don't have any infinite loops. 

I'm running in browser. 

Only reason I think there could be a bug is because when I comment out, `saveSync(fileByteArr, metaData.fileName);` , I don't get any rendor errors. I have tested it on other GB+ files and it work's fine. Just for some reason this one file is causing issues. 

(I'm essentially just sending file bytes from browser to browser and download on 'remote' browser for testing. Might be something about the file metadata that messes things up - idk, will update if I find anything out)

**Comment by dy** [comment]
Hm. Can you try
```js
require('save-file/src/to-blob')(thatBigFileData, 'abc')
```
?

**Comment by HaleemDream** [comment]
Tried it, didn't work, tested on another file and still fine.

The processing of files on my end is always the same for any file. No idea why it fails on this one file. All byte arrays are Int8Arrays. 

I think it has to be on my end since no one else had this issue. The file is .mkv but other .mkv files worked just fine. 

Thanks for the input

**Comment by dy** [comment]
Can you try to just
```js
require('to-array-buffer')(yourFileData)
```
and see if the error is still there?

Yes, stream writer for the purpose of huge files is def better solution.
Mb consider it here as well, as one of possible inputs.

**Comment by HaleemDream** [comment]
Unfortunately, that did not fix it ;(  

I did test out arraybuffer on other files and again, they still worked.

I tried waiting a couple seconds after the fileByteArray got saved in memory just in case It was possibly trying to download while data was still being set, that was not the case. 

Haha if you're interested, I can maybe PM you the file (just a tv show).  In any case, ill continue to try different things out and let you know.

Thanks

**Comment by HaleemDream** [comment]
Good news lol.

It for sure is on my end. I decided to just simply do a quick read of the file using FileReader and then download the results from the arraybuffer. That happens to work. Which is odd because it really shouldn't be any different from what i'm doing (moving bytes across browsers and then downloading the bytes). 

I'll have to make a comparison between the two and see what's different (byte arrays). Even if the contents of the array was somehow off, It should still write a file (File should just be corrupt - but I don't think this is the case either)?

**Comment by dy** [comment]
It depends on what exactly data you're saving, that can be a [to-array-buffer](https://ghub.io/to-array-buffer) error.

**Comment by HaleemDream** [comment]
@dy 

rip, bad news:

It works as an array buffer: 
````javascript
let file = bytes;
let reader = new FileReader();
let ab = reader.result;
let byteArray = new Int8Array(reader.result)

saveSync(ab, fileName); // WORKS
saveSync(byteArray, fileName) // FAILS
````

So I take it back, it has to do with the lib. Ill update with link to file.
